config/routes.rb
Rails.application.routes.draw do
  get 'users/show'

  devise_for :users
  get 'home/index'
  get 'home/faq'

   root 'home#index'

     resources :channels do 
             resources :feeds
     end
      resources :users

end

app/models/channel.rb
class Channel < ActiveRecord::Base
has_many :feeds
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
end

app/models/feed.rb
class Feed < ActiveRecord::Base	

belongs_to :user 
belongs_to :channel 
  has_attached_file :image, styles: { medium: "400x400>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :feeds

  has_attached_file :image, styles: { medium: "100x100>", thumb: "50x50>" } ,  default_url: "/assets/missing:style.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
	def new
		@channel = Channel.new
	end
    def create
    	@channel = Channel.new(channel_params)
    	if @channel.save
    		redirect_to root_path
    	else
    		render "new"
    	end
    end
	def index
	end
private
	def channel_params 
	params.require(:channel).permit(:name, :image , :description)
	end

end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
require 'rest_client'
	
	def index
		@feed = Feed.new
		@showfeeds = Feed.where(:channel_id => params[:channel_id]).order("created_at DESC")
		@resp = nil
	end 
	def create
		#client = HODClient.new('http://api.idolondemand.com', '2b7a646b-286e-40df-bd28-7e57f8e3739c')
		#@response = client.post('detectfaces',{'file' => Paperclip.io_adapters.for(feeds_params[:image]).read })
		#filea = Paperclip.io_adapters.for(feeds_params[:image]
		#client= HODClient.new("http://api.havenondemand.com/1/api/sync/","2b7a646b-286e-40df-bd28-7e57f8e3739c")
     if feeds_params[:content]
        source = RestClient.get "http://api.havenondemand.com/1/api/sync/analyzesentiment/v1?apikey=2b7a646b-286e-40df-bd28-7e57f8e3739c&text="+feeds_params[:content].to_s 
		sentiment = JSON.parse(source)
		
		concepts = RestClient.get "http://api.havenondemand.com/1/api/sync/extractconcepts/v1?apikey=2b7a646b-286e-40df-bd28-7e57f8e3739c&text="+feeds_params[:content].to_s 
	    concepts_extract = JSON.parse(concepts)
	    not_good = "no"
	    concepts_extract["concepts"].each do |conc| 
	    	if conc["concept"].to_s == "movies" ||  conc["concept"].to_s == "idiot" || conc["concept"].to_s == "let s go for movies!"
				not_good = "yes"
			end	    
	    end
	 end

		@feed = Feed.new(feeds_params)
        @feed.score = sentiment["aggregate"]["score"].to_f
		
		@feed.channel_id = params[:channel_id]
		@feed.user_id = current_user.id
		
		if feeds_params[:image]
			if not_good == "no"
			@response = RestClient.post('http://api.havenondemand.com/1/api/sync/detectfaces/v1?apikey=2b7a646b-286e-40df-bd28-7e57f8e3739c', :file => feeds_params[:image] )
		    @jso = JSON.parse(@response) 
			if @jso["face"].to_s == "[]"
			@feed.save	
		    else
		    flash[:alert] = "Please submit images related to educational material. People are detected in the photo you uploaded"
			end
			else
			 flash[:alert] = "Please submit posts that are educational in nature"	
			end
		    
		else
			if not_good == "no"
			@feed.save
			else
     		 flash[:alert] = "Please submit posts that are educational in nature"	
			end
		end
		redirect_to channel_feeds_path(:channel_id => params[:channel_id])
	end

	def destroy
		@feed = Feed.find(params[:id])
		if current_user.id == @feed.user_id
		@feed.destroy
	    end
		redirect_to user_path(current_user)
	end
private
	def feeds_params 
	params.require(:feed).permit(:content, :image)
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@allstudygrps = Channel.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  	@user = User.find(params[:id])
  	@showfeeds = Feed.where(:user_id => @user.id).order("created_at DESC")
  end
  def edit
  	@user = current_user
  end
  def update
  	@user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to @user
    else
      render 'edit'
    end
  end
  private
  def user_params
  		params.require(:user).permit(:first_name, :last_name, :image , :description)

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/channels/new.html.erb
<h2> Create New Study Group </h2>
<div class = "col-md-4 col-md-offset-4">
<%= form_for @channel, html: { multipart: true } do |form| %>
  <div class="field">
    <%= form.label :name_of_study_group %><br />
   <%= form.text_field :name , :class => 'form-control'%> <br/>
</div>

     <div class="field">
    <%= form.label :Image %><br />

  <%= form.file_field :image %> <br/>
  </div>
  <div class="field">
    <%= form.label :Description %><br />
   <%= form.text_area :description , :class => 'form-control' %> <br/>
</div>
  <%= form.submit  "Create New Study Group" , :class => "btn btn-lg btn-success"%>
<% end %>
</div>

app/views/feeds/index.html.erb
<h2>Study Group: <%= Channel.find(params[:channel_id]).name %> </h2>
<%= form_for :feed , url: channel_feeds_path(:channel_id => params[:channel_id]) , html: { multipart: true } do |f| %>

<%= f.text_area :content ,  class: 'form-control' ,:style => "margin-top:10px;" %>
     <%= f.file_field :image %>

<%= f.submit "Post" , class: "btn btn-large btn-success pull-right" %>
<% end %>
<br/><br/>
<% @showfeeds.each do |feed| %>
<div class="media">
  <div class="media-left">
    <%= link_to user_path(feed.user) do %>
<%= image_tag feed.user.image.url(:thumb) %>
    <% end %>
  </div>
  <div class="media-body">
    <h5 class="media-heading"><%= feed.user.first_name %> posted :-</h5>
    <% if feed.image.url(:medium).to_s != "/images/medium/missing.png" %>
<%= image_tag feed.image.url(:medium) %> <br/>
<% end %>

<%= feed.content %>
  </div>
</div>
 <br/>
	<hr/>		
	<% end %>
</div>

app/views/home/faq.html.erb
<div>
  <h2>Frequently Asked Questions</h2><br/>
  <p>Q1.) How do we define which posts are to be restricted from the group?</p>
  <p>EduBuddy uses <a href="https://www.havenondemand.com/"> HavenOnDemand API </a> from HP to understand your posts better. It then matches it with it's own database to see if the post fits the criteria of educational content.</p>
  
  <br/>
  <p>Q2.) </p>
  <p> </p>
  
  <br/>
  <p>Q1.) How do we define which posts are to be restricted from the group?</p>
  <p> </p>
  
</div>

app/views/home/index.html.erb
<% if current_user %> 
<h1> Study Groups Present </h1>
<% @allstudygrps.each do |grp| %>
<div class="col-xs-6 col-md-4">
<%= link_to  channel_feeds_path(:channel_id => grp.id) , :class => "thumbnail grp" do %>
     <%= image_tag grp.image.url(:medium) %>

     <div class="caption">
        <h3><%= grp.name %></h3>
        <p><%= grp.description %></p>
        </div>
    <% end %>
  </div>
<% end %>
<%= link_to "create new study group" ,  new_channel_path %> 

<% else %>

<h1> please sign in to access study groups </h1>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Edu Buddy</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="row">
<div class="col-md-8 col-md-offset-2">

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand">EduBuddy</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to root_path do  %><i class="glyphicon glyphicon-list-alt"> </i> study groups<% end %></li>
        <% if current_user %>
             <li><%= link_to current_user do %><i class="glyphicon glyphicon-user"> </i> my profile <% end %></li>
<% end %>
      </ul>
      
      <ul class="nav navbar-nav navbar-right">
              <li><%= link_to  home_faq_path do %> <i class="glyphicon glyphicon-question-sign"> </i> faq <% end %></li>

       <% if current_user %>
      	<li><%= link_to destroy_user_session_path , :method => "delete" do %> <i class="glyphicon glyphicon-log-out"> </i> logout <% end %></li>

       <% else %>
       
       <li><%= link_to new_user_session_path do %><i class="glyphicon glyphicon-log-in"> </i> login <% end %></li>
      	<li><%= link_to new_user_registration_path do %> <i class="glyphicon glyphicon-new-window"> </i> signup <% end %></li>
      
       <% end %>
        
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
</div>
</div>
<div class="row">
<div class="col-md-8 col-md-offset-2 panel panel-default">
       <% if alert %>
       <br/>
       <div class="alert alert-danger"><%= alert %></div>
<% end %>
<%= yield %>
 <p class="notice"><%= notice %></p>

</div>
</div>



</body>
</html>

app/views/users/edit.html.erb
<h1> Edit Your Profile </h1>
<div class = "col-md-4 col-md-offset-4">
<%= form_for @user, html: { multipart: true } do |form| %>
  <div class="field">
    <%= form.label :First_Name %><br />
   <%= form.text_field :first_name , :class => 'form-control'%> <br/>
</div>
  <div class="field">
    <%= form.label :Last_Name %><br />
   <%= form.text_field :last_name , :class => 'form-control' %><br/>
   </div>
     <div class="field">
    <%= form.label :Image %><br />

  <%= form.file_field :image %> <br/>
  </div>
  <div class="field">
    <%= form.label :Description %><br />
   <%= form.text_area :description, :class => 'form-control' %> <br/>
</div>
  <%= form.submit  "Update Profile" , :class => 'btn btn-primary'%>
<% end %>
</div>

app/views/users/show.html.erb
<div class="col-md-2"><br/>
<%= image_tag @user.image.url(:medium) %>

</div>
<div class="col-md-10">
<h1><%= @user.first_name %> <%= @user.last_name%></h1>
<p> <%= @user.description %> </p>
<% score = 0 %>
<% @showfeeds.each do |feed| %>
<% score = score + feed.score %>
<% end %>
<% if score > 0.7 %>
<%= image_tag "helpful" %> <span style="font-size:20px"> Helpful </span>
<% end %>

<br/>
<% if current_user == @user %>
<%= link_to "edit profile" , edit_user_path(current_user) , :class => "pull-right" %>
<% end %>
</div>
<div class="col-md-12">

<% if @showfeeds.count > 0 %>
<h3> Posts from <%= @user.first_name %> <%= @user.last_name%> </h3>
<% else %>
<h3> This user has not posted on anything yet </h3>
<% end %>
<% @showfeeds.each do |feed| %>
<div class="media">
  <div class="media-left">
    <%= link_to user_path(feed.user) do %>
<%= image_tag feed.user.image.url(:thumb) %>
    <% end %>
  </div>
  <div class="media-body">
    <h5 class="media-heading"><%= feed.user.first_name %> posted in <%= link_to Channel.find(feed.channel_id).name  , channel_feeds_path(:channel_id => feed.channel_id) %></h5>

 <% if current_user && current_user.id == feed.user.id %>
                    <%= link_to raw(" <span aria-hidden='true'>×</span>"), 
          channel_feed_path(channel_id: feed.channel_id, id: feed.id), 
           class: "pull-right close" , :method => :delete , data: {confirm: "Do you want to delete this feed item?"} %>
                     <% end %>
    <% if feed.image.url(:medium).to_s != "/images/medium/missing.png" %>
<%= image_tag feed.image.url(:medium) %> <br/>
<% end %>

<%= feed.content %>
 
  </div>

</div>
 <br/>
	<hr/>		
	<% end %>
</div>